import type { Metadata } from 'next';
import localFont from 'next/font/local';

import GlobalClientComponent from './GlobalClientComponent';
import Provider from './provider';
import './globals.css';

import { Toaster } from '@/components/ui/toaster';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen flex-col items-center justify-center`}
      >
        <GlobalClientComponent />
        <Provider>
          <main className="flex w-screen flex-1 flex-col items-center justify-center">
            {children}
          </main>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
